openapi: 3.0.3
info:
  title: Notifications Plugin - OpenAPI Specs
  description: |-
    Notifications Plugin - OpenAPI Specs
  version: 1.0.0
tags:
  - name: notifications
    description: notifications plugin
servers:
  - url: /
security:
  - BearerToken: []
paths:
  /api/notifications:
    get:
      tags:
        - "notifications"
      summary: Get user's notifications
      description: Get user's notifications
      operationId: getNotifications
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetNotifications"
      security:
        - BearerToken: []
    post:
      tags:
        - "notifications"
      summary: Create a notification
      description: Create a notification
      operationId: createNotification
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBody"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Notifications"
      security:
        - BearerToken: []
  /api/notifications/status:
    get:
      tags:
        - "notifications"
      summary: Get user's count of unread+read notifications
      description: Get user's count of unread+read notifications
      operationId: getStatus
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Count"
      security:
        - BearerToken: []
  /api/notifications/update:
    post:
      tags:
        - "notifications"
      summary: Set read/unread notifications
      description: Set read/unread notifications
      operationId: setRead
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SetReadRequest"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Notifications"
      security:
        - BearerToken: []
components:
  schemas:
    NotificationPayload:
      properties:
        title:
          type: string
        description:
          type: string
        link:
          type: string
        severity:
          type: string
          enum:
            - "critical"
            - "high"
            - "normal"
            - "low"
        topic:
          type: string
        scope:
          type: string
        icon:
          type: string
      required: [title]
    CreateBody:
      properties:
        recipients:
          type: object
          properties:
            type:
              type: string
              enum:
                - "broadcast"
                - "entity"
            entityRef:
              type: array
              items:
                type: string
            excludeEntityRef:
              type: array
              items:
                type: string
          required: ["type"]
        payload:
          $ref: "#/components/schemas/NotificationPayload"
    Notification:
      properties:
        id:
          type: string
        user:
          type: string
          nullable: true
        created:
          type: string
          format: date-time
        saved:
          type: string
          format: date-time
        read:
          type: number
        updated:
          type: string
          format: date-time
        origin:
          type: string
        payload:
          $ref: "#/components/schemas/NotificationPayload"
      required: [id, user, created, origin, payload]
    Notifications:
      type: array
      items:
        $ref: "#/components/schemas/Notification"
    Count:
      type: object
      properties:
        unread:
          type: number
        read:
          type: number
      required: [unread, read]
    SetReadRequest:
      type: object
      properties:
        ids:
          type: array
          items:
            type: string
          minItems: 1
        read:
          type: boolean
      required: [ids, read]
    GetNotifications:
      type: object
      properties:
        totalCount:
          type: number
        notifications:
          $ref: "#/components/schemas/Notifications"
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
      description: Bearer Token authentication
