apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: error-trigger-m2k
  namespace: sonataflow-infra
spec:
  broker: default
  filter:
    attributes:
      type: error
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: m2k
      namespace: default
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: transformation-saved-trigger-m2k
  namespace: sonataflow-infra
spec:
  broker: default
  filter:
    attributes:
      type: transformation_saved
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: m2k
      namespace: default
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: sonataflow-infra
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: m2k-save-transformation-event
  namespace: sonataflow-infra
spec:
  broker: default
  filter:
    attributes:
      type: save-transformation
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: m2k-save-transformation-func
      namespace: default
