# RPJ
rpj.url = ${RPJ_URL:https://rpj-rp-jira-sync-pre.apps.mig08.rhos-psi.cnv-qe.rhood.us}
quarkus.rest-client.rpj_json.url = ${rpj.url}

# Backstage Notifications service
quarkus.rest-client.notifications.url=${BACKSTAGE_NOTIFICATIONS_URL:http://backstage-backstage.rhdh-operator}
quarkus.openapi-generator.notifications.auth.BearerToken.bearer-token=${NOTIFICATIONS_BEARER_TOKEN:njmd0GEK3MO6z9Nv0UYdh3q}

# This property is used to select the log level, which controls the amount
# of information logged on HTTP requests based on the severity of the events.
# Possible values: OFF, FATAL, ERROR, WARN, INFO, DEBUG, ALL.
# and see https://quarkus.io/guides/logging for documentation
quarkus.log.category."org.apache.http".level=INFO
quarkus.log.level=INFO
